// Generates .env.template files from existing env maps
// Strips values but preserves keys and optional comments

export type TemplateOptions = {
  includeComments: boolean;
  placeholderStyle: "empty" | "type" | "example";
};

export type EnvMap = Map<string, string>;

export function defaultTemplateOptions(): TemplateOptions {
  return {
    includeComments: true,
    placeholderStyle: "empty",
  };
}

export function parsePlaceholderStyle(
  raw: string | undefined
): TemplateOptions["placeholderStyle"] {
  if (raw === "type" || raw === "example") return raw;
  return "empty";
}

export function generatePlaceholder(
  key: string,
  value: string,
  style: TemplateOptions["placeholderStyle"]
): string {
  if (style === "empty") return "";
  if (style === "example") return value;
  // type: infer a rough type hint
  if (value === "true" || value === "false") return "<boolean>";
  if (/^\d+$/.test(value)) return "<number>";
  if (value.startsWith("http")) return "<url>";
  return "<string>";
}

export function generateTemplate(
  envMap: EnvMap,
  options: Partial<TemplateOptions> = {}
): string {
  const opts = { ...defaultTemplateOptions(), ...options };
  const lines: string[] = [];

  if (opts.includeComments) {
    lines.push("# Generated by envdiff — fill in values before use");
    lines.push("");
  }

  for (const [key, value] of envMap.entries()) {
    const placeholder = generatePlaceholder(key, value, opts.placeholderStyle);
    lines.push(`${key}=${placeholder}`);
  }

  return lines.join("\n");
}

export function mergeTemplates(base: EnvMap, override: EnvMap): EnvMap {
  const merged = new Map(base);
  for (const [key, value] of override.entries()) {
    if (!merged.has(key)) {
      merged.set(key, value);
    }
  }
  return merged;
}
