import {
  generatePlaceholder,
  generateTemplate,
  mergeTemplates,
  parsePlaceholderStyle,
  defaultTemplateOptions,
} from "./templater";

const makeMap = (obj: Record<string, string>) => new Map(Object.entries(obj));

describe("parsePlaceholderStyle", () => {
  it("returns empty for undefined", () => {
    expect(parsePlaceholderStyle(undefined)).toBe("empty");
  });
  it("returns type for 'type'", () => {
    expect(parsePlaceholderStyle("type")).toBe("type");
  });
  it("returns example for 'example'", () => {
    expect(parsePlaceholderStyle("example")).toBe("example");
  });
  it("falls back to empty for unknown", () => {
    expect(parsePlaceholderStyle("weird")).toBe("empty");
  });
});

describe("generatePlaceholder", () => {
  it("returns empty string for empty style", () => {
    expect(generatePlaceholder("KEY", "somevalue", "empty")).toBe("");
  });
  it("returns the original value for example style", () => {
    expect(generatePlaceholder("KEY", "hello", "example")).toBe("hello");
  });
  it("infers boolean type", () => {
    expect(generatePlaceholder("FLAG", "true", "type")).toBe("<boolean>");
  });
  it("infers number type", () => {
    expect(generatePlaceholder("PORT", "3000", "type")).toBe("<number>");
  });
  it("infers url type", () => {
    expect(generatePlaceholder("API", "https://example.com", "type")).toBe("<url>");
  });
  it("falls back to string type", () => {
    expect(generatePlaceholder("NAME", "myapp", "type")).toBe("<string>");
  });
});

describe("generateTemplate", () => {
  const map = makeMap({ PORT: "3000", DEBUG: "true", API_URL: "https://api.example.com" });

  it("includes header comment by default", () => {
    const out = generateTemplate(map);
    expect(out).toContain("# Generated by envdiff");
  });

  it("strips values in empty mode", () => {
    const out = generateTemplate(map, { placeholderStyle: "empty" });
    expect(out).toContain("PORT=");
    expect(out).not.toContain("PORT=3000");
  });

  it("preserves values in example mode", () => {
    const out = generateTemplate(map, { placeholderStyle: "example", includeComments: false });
    expect(out).toContain("PORT=3000");
  });

  it("omits comment when includeComments is false", () => {
    const out = generateTemplate(map, { includeComments: false });
    expect(out).not.toContain("#");
  });
});

describe("mergeTemplates", () => {
  it("adds keys from override that are missing in base", () => {
    const base = makeMap({ A: "1" });
    const override = makeMap({ B: "2" });
    const result = mergeTemplates(base, override);
    expect(result.get("B")).toBe("2");
  });

  it("does not overwrite existing keys", () => {
    const base = makeMap({ A: "1" });
    const override = makeMap({ A: "99" });
    const result = mergeTemplates(base, override);
    expect(result.get("A")).toBe("1");
  });
});
